{% set name = "vizro" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vizro-{{ version }}.tar.gz
  sha256: cf287de5e8f0fa904456c8c692dc6cec1f25c6a6fdb64b19372602e8d5d2bae2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - dash >=2.14.1,!=2.16.0
    - dash-bootstrap-components
    - dash-ag-grid >=31.0.0
    - pandas
    - pydantic >=1.10.13
    - dash-mantine-components
    - numpy >=1.22.2
    - setuptools >=65.5.1
    - werkzeug >=3.0.1
# Not in Grayskull Rendered Recipe
    #- dash-daq
    #- ipython >=8.10.0
    #- tornado >=6.3.2
    #- markupsafe

test:
  imports:
    - vizro
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Vizro is a package to facilitate visual analytics.
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
