{% set name = "vizro" %}
{% set version = "0.1.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vizro-{{ version }}.tar.gz
  sha256: d36c532240fc5d14ae5d2e8b6ef445654d79e842c9473e8432c82b9f9b26b5b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - packaging
    - python >={{ python_min }}
    - dash >=2.18.0,<3
# dash 2.18.1 has requirement Flask<3.1,>=1.0.4, but you have flask 3.1.0.
    - flask >=1.0.4,<3.1
# dash 2.18.1 has requirement Werkzeug<3.1, but you have werkzeug 3.1.3.
    - werkzeug <3.1
    - dash-bootstrap-components <2.0.0
    - dash-core-components
    - dash-html-components
    - dash-table
# dash-bootstrap-components 2.0.0 has requirement dash>=3.0.0, but you have dash 2.18.2.
    - dash-ag-grid >=31.0.0
    - pandas >=2
    - plotly >=5.24.0
    - pydantic >=2.7.0
    - dash-mantine-components >=0.15.1,<0.16.dev0
    - flask-caching >=2
    - wrapt >=1
    - black
    - autoflake
# Not needed anymore 
    #- ruff
    #- numpy >=1.22.2
    #- setuptools >=65.5.1
# Not in Grayskull Rendered Recipe
    #- dash-daq
    #- ipython >=8.10.0
    #- tornado >=6.3.2
    #- markupsafe

test:
  imports:
    - vizro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Vizro is a package to facilitate visual analytics.
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
