{% set name = "vizro" %}
{% set version = "0.1.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vizro-{{ version }}.tar.gz
  sha256: 95c6e7fb8e2ac22715d3bf79aa8e58fc0b704a2a9c66eb0f85eca64cde4c7d13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python-box
    - python >={{ python_min }}
    - dash >=3.1.1
    - dash-bootstrap-components >=2
    - dash-ag-grid >=31.3.1
    - dash-mantine-components >=1
    - pandas >=2
    - plotly >=5.24.0
    - pydantic >=2.7.0
    - flask-caching >=2
    - wrapt >=1
    - black
    - autoflake
    - packaging

test:
  imports:
    - vizro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Vizro is a low-code framework for building high-quality data visualization apps.
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - examples/visual-vocabulary/LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
