{% set name = "vizro" %}
{% set version = "0.1.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vizro-{{ version }}.tar.gz
  sha256: 848c1a7a27253b0154c7436874cdba388eca68f5d79cbf8b7038715e01682357

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dash >=2.17.1,<3
# dash 2.18.1 has requirement Flask<3.1,>=1.0.4, but you have flask 3.1.0.
    - flask >=1.0.4,<3.1
# dash 2.18.1 has requirement Werkzeug<3.1, but you have werkzeug 3.1.3.
    - werkzeug <3.1
    - dash-bootstrap-components
    - dash-ag-grid >=31.0.0
    - pandas >=2
    - plotly >=5.12.0
    - pydantic >=1.10.16
    - dash-mantine-components <0.13.0
    - flask-caching >=2
    - wrapt >=1
    - black
    - autoflake
# Not needed anymore 
    #- ruff
    #- numpy >=1.22.2
    #- setuptools >=65.5.1
# Not in Grayskull Rendered Recipe
    #- dash-daq
    #- ipython >=8.10.0
    #- tornado >=6.3.2
    #- markupsafe

test:
  imports:
    - vizro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Vizro is a package to facilitate visual analytics.
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
