{% set name = "vizro" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vizro-{{ version }}.tar.gz
  sha256: 157bfe08d62583a641218280c1c36e54a8636e05a1ca79588434385403fc8979

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - dash >=2.11
    - dash-bootstrap-components
    - pandas
    - pydantic >=1.10.13,<2
    - dash-daq
    - ipython >=8.10.0
    - numpy >=1.22.2
    - tornado >=6.3.2
    - setuptools >=65.5.1
    - markupsafe

test:
  imports:
    - vizro

about:
  summary: Vizro is a package to facilitate visual analytics.
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
